### ISSUE TITLE
Make unittests

### ISSUE THREAD

**Issue by dnmellen** [Feverup/lilliput#3]
Unittests covering:
- Creating a shortened link

**Comment by belfazt** [comment]
Hello, I'll try to help you with this :)

**Comment by aniketmaithani** [comment]
@dnmellen Nice Project btw! I was thinking if we could add `PyTest` as a default test runner that would be great. Your take?

**Comment by dnmellen** [comment]
@aniketmaithani Thanks! Go ahead, but start from this commit https://github.com/dnmellen/lilliput/commit/2944b53af70e46af3944a051cd01b314d2e5d9b6, since that is already Django 1.10 compatible
